### ISSUE TITLE
Question About rskg.xlsx

### ISSUE THREAD

**Issue by Mr-Second** [kdy2021/SR-RSKG#1]
In sheet triple of rskg.xlsx, Why is the expression for F1-F27 different from the expression for F28-F191?
![1](https://user-images.githubusercontent.com/38907693/134912381-c02dd37b-59c9-4330-9966-c366c5772f38.png)
![2](https://user-images.githubusercontent.com/38907693/134912389-3810e0b8-61a6-4240-a4da-319ab41b1d41.png)

**Comment by Mr-Second** [comment]
the former is looking up for column B, the latter is looking up for column C

**Comment by DsglSheng** [comment]
> the former is looking up for column B, the latter is looking up for column C

您好，请问您这个问题解决了吗，我也发现了这个问题，是不是1到27误写成查找B栏了

**Comment by Mr-Second** [comment]
> 

应该是的

**Comment by DsglSheng** [comment]
> 应该是的
非常感谢！小白还想请教一下您，我的neo4j图谱已经建成了，但是后续知识图谱如何做表示并参与到零样本学习中，您有了解过吗，有相关的工作或代码可以推荐一下嘛，这方面困扰了我很久，再次感谢您！

**Comment by Mr-Second** [comment]
> > 应该是的
> > 非常感谢！小白还想请教一下您，我的neo4j图谱已经建成了，但是后续知识图谱如何做表示并参与到零样本学习中，您有了解过吗，有相关的工作或代码可以推荐一下嘛，这方面困扰了我很久，再次感谢您！

俺也是小白😂，之前看过一些zsl结合kg的工作
https://arxiv.org/abs/2103.00070
https://arxiv.org/abs/2006.10713
https://github.com/BatsResearch/zsl-kg
希望对你有帮助

**Comment by DsglSheng** [comment]
> > > 应该是的
> > > 非常感谢！小白还想请教一下您，我的neo4j图谱已经建成了，但是后续知识图谱如何做表示并参与到零样本学习中，您有了解过吗，有相关的工作或代码可以推荐一下嘛，这方面困扰了我很久，再次感谢您！
> 
> 俺也是小白😂，之前看过一些zsl结合kg的工作 https://arxiv.org/abs/2103.00070 https://arxiv.org/abs/2006.10713 https://github.com/BatsResearch/zsl-kg 希望对你有帮助

谢谢您，万分感谢！！！
